name: ci/github-actions

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  winBuild:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: nuget/setup-nuget@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Install .NET MAUI
      shell: pwsh
      run: |
        & dotnet nuget locals all --clear
        & dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
        & dotnet workload install android ios maccatalyst tvos macos maui wasm-tools maui-maccatalyst --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Clean
      uses: cake-build/cake-action@v2
      with:
        script-path: .build/build.cake
        target: Clean
    - name: Restore
      uses: cake-build/cake-action@v2
      with:
        script-path: .build/build.cake
        target: Restore
    - name: Build Libs
      uses: cake-build/cake-action@v2
      with:
        script-path: .build/build.cake
        target: BuildLibs
    - name: Build Clients
      uses: cake-build/cake-action@v2
      with:
        script-path: .build/build.cake
        target: BuildClients
    - name: Builds Tests
      uses: cake-build/cake-action@v2
      with:
        script-path: .build/build.cake
        target: BuildTests
    - name: Run Tests
      uses: cake-build/cake-action@v2
      with:
        script-path: .build/build.cake
        target: RunTests
    - name: Build Plugin.BLE NuGet
      run: msbuild .\Source\Plugin.BLE\Plugin.BLE.csproj /p:Configuration=Release /t:restore,build,pack /p:PackageOutputPath=./nuget /p:Version=$(git describe) /p:ContinuousIntegrationBuild=true /p:DeterministicSourcePaths=false
    - name: Build MVVMCross.Plugins.BLE NuGet
      run: msbuild .\Source\MvvmCross.Plugins.BLE\MvvmCross.Plugins.BLE.csproj /p:Configuration=Release /t:restore,build,pack /p:PackageOutputPath=./nuget /p:Version=$(git describe) /p:ContinuousIntegrationBuild=true /p:DeterministicSourcePaths=false
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: nupkg
        path: ./Source/*/nuget/*Plugin.BLE*.nupkg

  macBuild:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup XCode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Install .NET MAUI
      run: |
        dotnet nuget locals all --clear
        dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
        dotnet workload install android ios maccatalyst tvos macos maui wasm-tools maui-maccatalyst --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
    - name: Install Android tools
      run: ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-34" "platforms;android-33" "build-tools;34.0.0" "platform-tools"
    - name: Build Plugin.BLE NuGet
      run: dotnet build ./Source/Plugin.BLE/Plugin.BLE.csproj /p:Configuration=Release /t:restore,build,pack /p:Version=$(git describe) /p:ContinuousIntegrationBuild=true /p:DeterministicSourcePaths=false
    - name: Build MVVMCross.Plugins.BLE NuGet
      run: dotnet build ./Source/MvvmCross.Plugins.BLE/MvvmCross.Plugins.BLE.csproj /p:Configuration=Release /t:restore,build,pack /p:Version=$(git describe) /p:ContinuousIntegrationBuild=true /p:DeterministicSourcePaths=false
    - name: Build MAUI sample
      run: dotnet build ./Source/BLE.Client/BLE.Client.Maui/BLE.Client.Maui.csproj /p:Configuration=Release /t:restore,build /p:Version=$(git describe) /p:ContinuousIntegrationBuild=true /p:DeterministicSourcePaths=false

  linuxBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: 8.0.x
    - name: Install workloads
      run: dotnet workload install android wasm-tools maui-android
    - name: Install Android tools
      run: ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools"
    - name: Build Plugin.BLE NuGet
      run: dotnet build ./Source/Plugin.BLE/Plugin.BLE.csproj -p:Configuration=Release -t:restore,build,pack -p:Version=$(git describe) -p:ContinuousIntegrationBuild=true -p:DeterministicSourcePaths=false
    - name: Build MVVMCross.Plugins.BLE NuGet
      run: dotnet build ./Source/MvvmCross.Plugins.BLE/MvvmCross.Plugins.BLE.csproj -p:Configuration=Release -t:restore,build,pack -p:Version=$(git describe) -p:ContinuousIntegrationBuild=true -p:DeterministicSourcePaths=false
    - name: Build MAUI sample
      run: dotnet build ./Source/BLE.Client/BLE.Client.Maui/BLE.Client.Maui.csproj -p:Configuration=Release -t:restore,build -p:Version=$(git describe) -p:ContinuousIntegrationBuild=true -p:DeterministicSourcePaths=false
